import "@/app/(styles)/globals.css";
import type { Metadata } from "next";

import { Inter, Fira_Code } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const firacode = Fira_Code({ subsets: ["latin"], variable: "--font-mono" });

export const metadata: Metadata = {
  title: {
    template: "%s - <crescitelli.dev/>",
    default: "Welcome - <crescitelli.dev/>",
  },
  description: "Generated by create next app",
};

interface Props {
  readonly children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={`${inter.variable} ${firacode.variable}`}>
      <body className="min-h-screen w-full bg-grid">{children}</body>
    </html>
  );
}
